#!/usr/bin/env python3
"""
Build a redistributable Indonesian audio pack from CC0 Lingua Libre recordings
on Wikimedia Commons.

Outputs:
  app/src/main/assets/tts_audio.m4a
  app/src/main/assets/tts_index.tsv
  build/audio/audio_build_report.json

The index hashes the exact learning-app text, not any UI numbering.
Only exact/normalized transcription matches are accepted; no TTS or synthetic
audio is generated by this script.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import unicodedata
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


API = "https://commons.wikimedia.org/w/api.php"
CATEGORY = "Category:Lingua Libre pronunciation-ind"
CC0_QID = "Q6938433"
USER_AGENT = "IndonesianEngineerApp/0.7 audio-builder (GitHub Actions)"
PAUSE_MS = 120
TARGET_LINES = 3000

PUNCTUATION_EDGES = " \\t\\r\\n\\\"'“”‘’.,!?;:，。！？；：、（）()[]{}"


def request_json(params: dict[str, Any]) -> dict[str, Any]:
    params = dict(params)
    params["format"] = "json"
    url = API + "?" + urllib.parse.urlencode(params)
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def fetch_category_members() -> list[dict[str, Any]]:
    members: list[dict[str, Any]] = []
    cont: dict[str, Any] = {}

    while True:
        params = {
            "action": "query",
            "list": "categorymembers",
            "cmtitle": CATEGORY,
            "cmnamespace": "6",
            "cmlimit": "500",
        }
        params.update(cont)
        data = request_json(params)
        members.extend(data.get("query", {}).get("categorymembers", []))
        if "continue" not in data:
            break
        cont = data["continue"]

    return [m for m in members if m.get("title", "").lower().endswith(".wav")]


def fetch_image_info(titles: list[str]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for start in range(0, len(titles), 50):
        batch = titles[start:start + 50]
        data = request_json({
            "action": "query",
            "prop": "imageinfo",
            "titles": "|".join(batch),
            "iiprop": "url|size|mime",
            "iiurlwidth": 0,
        })
        for page in data.get("query", {}).get("pages", {}).values():
            title = page.get("title")
            info = (page.get("imageinfo") or [{}])[0]
            if title and info.get("url"):
                result[title] = info
    return result


def fetch_media_entities(pageids: list[int]) -> dict[int, dict[str, Any]]:
    result: dict[int, dict[str, Any]] = {}
    for start in range(0, len(pageids), 50):
        batch = pageids[start:start + 50]
        ids = "|".join("M" + str(pid) for pid in batch)
        data = request_json({
            "action": "wbgetentities",
            "ids": ids,
            "props": "claims",
        })
        for entity in data.get("entities", {}).values():
            if entity.get("missing"):
                continue
            entity_id = entity.get("id", "")
            if not entity_id.startswith("M"):
                continue
            try:
                result[int(entity_id[1:])] = entity
            except ValueError:
                continue
    return result


def claim_values(entity: dict[str, Any], prop: str) -> list[Any]:
    values: list[Any] = []
    for claim in entity.get("claims", {}).get(prop, []):
        snak = claim.get("mainsnak", {})
        dv = snak.get("datavalue", {})
        if "value" in dv:
            values.append(dv["value"])
    return values


def get_transcription(entity: dict[str, Any]) -> str:
    for value in claim_values(entity, "P9533"):
        if isinstance(value, dict):
            text = value.get("text", "")
        else:
            text = str(value)
        if text:
            return text
    return ""


def get_license_qids(entity: dict[str, Any]) -> set[str]:
    qids: set[str] = set()
    for value in claim_values(entity, "P275"):
        if isinstance(value, dict) and value.get("id"):
            qids.add(value["id"])
    return qids


def get_speaker_ids(entity: dict[str, Any]) -> list[str]:
    ids: list[str] = []
    for value in claim_values(entity, "P10894"):
        if isinstance(value, dict) and value.get("id"):
            ids.append(value["id"])
    return ids


def normalize_text(text: str) -> str:
    text = unicodedata.normalize("NFC", text)
    text = text.replace("\u00a0", " ")
    text = re.sub(r"\s+", " ", text).strip().casefold()
    text = text.strip(PUNCTUATION_EDGES)
    return text


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def collect_required_texts(root: Path) -> tuple[list[str], Counter[str]]:
    texts: dict[str, str] = {}
    sources: Counter[str] = Counter()

    def add(text: str, source: str) -> None:
        text = text.strip()
        if not text:
            return
        key = normalize_text(text)
        if not key:
            return
        texts.setdefault(key, text)
        sources[key] += 1

    for i in range(1, 12):
        path = root / "app" / "src" / "main" / "assets" / f"words_{i:02d}.tsv"
        for row in read_tsv(path):
            add(row.get("indonesian", ""), "vocabulary")

    sentences = root / "app" / "src" / "main" / "assets" / "sentences.tsv"
    if sentences.exists():
        for row in read_tsv(sentences):
            add(row.get("indonesian", ""), "sentence")

    scenes = root / "app" / "src" / "main" / "assets" / "scenes.tsv"
    if scenes.exists():
        for row in read_tsv(scenes):
            add(row.get("indonesian", ""), "scene")

    letters = root / "app" / "src" / "main" / "assets" / "letters.tsv"
    if letters.exists():
        for row in read_tsv(letters):
            add(row.get("example", ""), "letter_example")

    return list(texts.values()), sources


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, check=True)


def ffprobe_duration(path: Path) -> float:
    output = subprocess.check_output([
        "ffprobe",
        "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path),
    ], text=True).strip()
    return float(output)


def download_file(url: str, destination: Path) -> None:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=90) as response, destination.open("wb") as out:
        shutil.copyfileobj(response, out)


def make_concat_audio(selected: list[dict[str, Any]], temp_root: Path, output_path: Path) -> list[dict[str, Any]]:
    normalized_dir = temp_root / "normalized"
    normalized_dir.mkdir(parents=True, exist_ok=True)

    index_rows: list[dict[str, Any]] = []
    running_ms = 0

    for number, item in enumerate(selected, start=1):
        raw_path = temp_root / f"raw_{number}.wav"
        normalized_path = normalized_dir / f"{number:04d}.wav"

        cache_file = Path(item["cache_path"])
        if cache_file.exists():
            shutil.copy2(cache_file, raw_path)
        else:
            download_file(item["url"], raw_path)
            cache_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(raw_path, cache_file)

        run([
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(raw_path),
            "-ac", "1",
            "-ar", "24000",
            "-sample_fmt", "s16",
            str(normalized_path),
        ])

        duration_ms = max(1, round(ffprobe_duration(normalized_path) * 1000))
        index_rows.append({
            "sha256": sha256(item["target_text"]),
            "start_ms": running_ms,
            "duration_ms": duration_ms,
            "original_text": item["target_text"],
            "source_file": item["title"],
            "source_url": item["description_url"],
            "license": "CC0-1.0",
            "speaker_ids": ",".join(item.get("speaker_ids", [])),
        })

        running_ms += duration_ms + PAUSE_MS

    concat_file = temp_root / "concat.txt"
    with concat_file.open("w", encoding="utf-8") as fh:
        for number in range(1, len(selected) + 1):
            fh.write("file '" + str(normalized_dir / f"{number:04d}.wav").replace("'", "'\\''") + "'\n")
            fh.write(f"duration {ffprobe_duration(normalized_dir / f'{number:04d}.wav'):.6f}\n")

    pause_file = temp_root / "pause.wav"
    run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "lavfi",
        "-i", f"anullsrc=r=24000:cl=mono",
        "-t", f"{PAUSE_MS / 1000:.3f}",
        "-ar", "24000",
        "-ac", "1",
        "-sample_fmt", "s16",
        str(pause_file),
    ])

    # Build a single concatenated PCM WAV with explicit pauses, then encode AAC/M4A.
    files: list[Path] = []
    for number in range(1, len(selected) + 1):
        files.append(normalized_dir / f"{number:04d}.wav")
        if number != len(selected):
            files.append(pause_file)

    with concat_file.open("w", encoding="utf-8") as fh:
        for path in files:
            fh.write("file '" + str(path).replace("'", "'\\''") + "'\n")

    temp_wav = temp_root / "all.wav"
    run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "concat", "-safe", "0",
        "-i", str(concat_file),
        "-c:a", "pcm_s16le",
        str(temp_wav),
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-i", str(temp_wav),
        "-c:a", "aac",
        "-b:a", "48k",
        "-movflags", "+faststart",
        str(output_path),
    ])

    return index_rows


def write_index(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh, delimiter="\t", lineterminator="\n")
        writer.writerow([
            "sha256", "start_ms", "duration_ms", "original_text",
            "source_file", "source_url", "license", "speaker_ids"
        ])
        for row in rows:
            writer.writerow([
                row["sha256"],
                row["start_ms"],
                row["duration_ms"],
                row["original_text"],
                row["source_file"],
                row["source_url"],
                row["license"],
                row["speaker_ids"],
            ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-lines", type=int, default=TARGET_LINES)
    parser.add_argument("--max-lines", type=int, default=3200)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()

    root = args.root.resolve()
    required_texts, required_sources = collect_required_texts(root)
    required_map = {normalize_text(text): text for text in required_texts}

    cache_root = root / ".cache" / "indonesian-audio"
    cache_root.mkdir(parents=True, exist_ok=True)

    print(f"Required unique learning texts: {len(required_texts)}")
    print("Querying Wikimedia Commons category...")

    members = fetch_category_members()
    titles = [m["title"] for m in members]
    infos = fetch_image_info(titles)
    entities = fetch_media_entities([int(m["pageid"]) for m in members if m.get("pageid")])

    candidates: dict[str, list[dict[str, Any]]] = defaultdict(list)
    source_count = 0

    for member in members:
        title = member.get("title", "")
        pageid = member.get("pageid")
        if not title or not pageid:
            continue

        entity = entities.get(int(pageid), {})
        transcription = get_transcription(entity)
        normalized = normalize_text(transcription)
        if not normalized:
            continue

        licenses = get_license_qids(entity)
        if CC0_QID not in licenses:
            continue

        info = infos.get(title)
        if not info:
            continue
        if info.get("mime") not in {"audio/wav", "audio/x-wav"}:
            continue

        target_text = required_map.get(normalized)
        if target_text is None:
            continue

        candidate = {
            "title": title,
            "pageid": int(pageid),
            "url": info["url"],
            "description_url": "https://commons.wikimedia.org/wiki/" + urllib.parse.quote(title.replace(" ", "_"), safe="/:(),"),
            "target_text": target_text,
            "speaker_ids": get_speaker_ids(entity),
            "cache_path": str(cache_root / (hashlib.sha1(title.encode("utf-8")).hexdigest() + ".wav")),
        }
        candidates[normalized].append(candidate)
        source_count += 1

    # Deterministic selection: prefer the first lexicographically sorted CC0 recording
    # for each exact target transcript. This keeps builds reproducible.
    selected: list[dict[str, Any]] = []
    for normalized in sorted(candidates):
        options = sorted(candidates[normalized], key=lambda item: item["title"])
        selected.append(options[0])

    covered = len(selected)
    print(f"Exact learning-text audio matches: {covered}")

    if covered < args.min_lines:
        report = {
            "status": "FAIL",
            "required_learning_texts": len(required_texts),
            "exact_learning_audio_matches": covered,
            "minimum_audio_lines": args.min_lines,
            "candidate_category_files": len(members),
            "cc0_matching_files": source_count,
            "message": "Not enough exact CC0 Indonesian recordings to build the required audio floor.",
        }
        report_path = root / "build" / "audio" / "audio_build_report.json"
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 2

    # Cap the shipped pack for APK size while preserving deterministic ordering.
    selected = selected[:args.max_lines]

    assets = root / "app" / "src" / "main" / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    audio_path = assets / "tts_audio.m4a"
    index_path = assets / "tts_index.tsv"

    with tempfile.TemporaryDirectory(prefix="indonesian_audio_") as temp_dir:
        rows = make_concat_audio(selected, Path(temp_dir), audio_path)

    write_index(index_path, rows)

    report = {
        "status": "PASS",
        "source": "Wikimedia Commons / Lingua Libre pronunciation-ind",
        "source_category_files": len(members),
        "required_learning_texts": len(required_texts),
        "exact_learning_audio_matches": covered,
        "audio_lines": len(rows),
        "pause_ms": PAUSE_MS,
        "minimum_audio_lines": args.min_lines,
        "maximum_audio_lines": args.max_lines,
        "license_required": "CC0-1.0",
        "required_sources": dict(required_sources),
        "audio_asset_bytes": audio_path.stat().st_size,
        "index_asset_bytes": index_path.stat().st_size,
    }

    report_path = root / "build" / "audio" / "audio_build_report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
